services:
  orwell-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: orwell-elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=$ELASTIC_SECURITY
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    env_file:
      - path: .env
        required: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_HOST_PORT:-9200}:${ELASTICSEARCH_PORT:-9200}"
      - "${ELASTICSEARCH_HOST_PORT_2:-9300}:${ELASTICSEARCH_PORT_2:-9300}"
    healthcheck:
      test: [ "CMD-SHELL", "curl -u ${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD} -s http://localhost:9200/_cluster/health | grep '\"status\":\"green\"' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - orwellnet
  orwell-kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: orwell-kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://orwell-elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    env_file:
      - path: .env
        required: true
    ports:
      - "${KIBANA_HOST_PORT:-5601}:${KIBANA_PORT:-5601}"
    networks:
      - orwellnet
    depends_on:
      - orwell-elasticsearch
  orwell:
    image: mirilianorwell/orwell:1.0.0
    container_name: orwell
    ports:
      - "${ORWELL_HOST_PORT:-26490}:${ORWELL_PORT:-8080}"
    env_file:
      - path: .env
        required: true
    volumes:
      - ./appsettings.json:/app/appsettings.json # Mount your local config file
    networks:
      - orwellnet
    depends_on:
      - orwell-elasticsearch

volumes:
  es_data:
    driver: local

networks:
  orwellnet:
    driver: bridge
